// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RestClientSDKLibrary
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for RestClientSDKLibraryClient.
    /// </summary>
    public static partial class RestClientSDKLibraryClientExtensions
    {
            /// <summary>
            /// Provides an AI-generated optimal countermove to a tic-tac-toe game state
            /// by using minimax.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// </param>
            public static object ProcessComplexInput(this IRestClientSDKLibraryClient operations, InputPayload body = default(InputPayload))
            {
                return Task.Factory.StartNew(s => ((IRestClientSDKLibraryClient)s).ProcessComplexInputAsync(body), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Provides an AI-generated optimal countermove to a tic-tac-toe game state
            /// by using minimax.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ProcessComplexInputAsync(this IRestClientSDKLibraryClient operations, InputPayload body = default(InputPayload), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ProcessComplexInputWithHttpMessagesAsync(body, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
